services:
    database:
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=testuser
            - MYSQL_PASSWORD=admin123
            - MYSQL_DATABASE=backend
        image: mysql/mysql-server:5.7
        volumes:
            - /usercode/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    web:
        build: .
        links:
            - database:backenddb
        ports:
            - 5000:5000
        volumes:
            - /usercode/:/code
version: "3"
